name: Build Notepad++ (x86)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build full solution
        run: |
          msbuild PowerEditor\visual.net\notepadPlus.sln ^
            /t:Build ^
            /p:Configuration=Release ^
            /p:Platform=Win32

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notepadpp-x86
          path: PowerEditor\bin\*
          
